# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'simpleGUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(963, 895)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(False)
        MainWindow.setStyleSheet("background-color: rgb(250, 250, 250);\n"
"border-color: rgb(199, 199, 199);\n"
"border-bottom-color: rgb(255, 255, 255);")
        MainWindow.setIconSize(QtCore.QSize(64, 64))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.segmentation = QtWidgets.QFrame(self.centralwidget)
        self.segmentation.setGeometry(QtCore.QRect(0, 311, 211, 133))
        self.segmentation.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.segmentation.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.segmentation.setFrameShadow(QtWidgets.QFrame.Raised)
        self.segmentation.setObjectName("segmentation")
        self.activateLabel = QtWidgets.QComboBox(self.segmentation)
        self.activateLabel.setGeometry(QtCore.QRect(3, 25, 205, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.activateLabel.setFont(font)
        self.activateLabel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.activateLabel.setObjectName("activateLabel")
        self.paintOver = QtWidgets.QComboBox(self.segmentation)
        self.paintOver.setGeometry(QtCore.QRect(3, 78, 206, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.paintOver.setFont(font)
        self.paintOver.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.paintOver.setObjectName("paintOver")
        self.labelTitle = QtWidgets.QLineEdit(self.segmentation)
        self.labelTitle.setGeometry(QtCore.QRect(0, 0, 211, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.labelTitle.setFont(font)
        self.labelTitle.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.labelTitle.setReadOnly(True)
        self.labelTitle.setObjectName("labelTitle")
        self.paintTitle = QtWidgets.QLineEdit(self.segmentation)
        self.paintTitle.setGeometry(QtCore.QRect(0, 53, 211, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.paintTitle.setFont(font)
        self.paintTitle.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.paintTitle.setReadOnly(True)
        self.paintTitle.setObjectName("paintTitle")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.segmentation)
        self.lineEdit_7.setGeometry(QtCore.QRect(1, 106, 61, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.opacity = QtWidgets.QScrollBar(self.segmentation)
        self.opacity.setGeometry(QtCore.QRect(67, 107, 138, 21))
        self.opacity.setStyleSheet("background-color: rgb(149, 149, 149);")
        self.opacity.setOrientation(QtCore.Qt.Horizontal)
        self.opacity.setObjectName("opacity")
        self.buttonGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.buttonGroup.setGeometry(QtCore.QRect(0, 230, 211, 81))
        self.buttonGroup.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.buttonGroup.setTitle("")
        self.buttonGroup.setObjectName("buttonGroup")
        self.b1 = QtWidgets.QPushButton(self.buttonGroup)
        self.b1.setGeometry(QtCore.QRect(2, 2, 48, 48))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        self.b1.setFont(font)
        self.b1.setText("")
        self.b1.setAutoExclusive(True)
        self.b1.setFlat(False)
        self.b1.setObjectName("b1")
        self.b2 = QtWidgets.QPushButton(self.buttonGroup)
        self.b2.setGeometry(QtCore.QRect(50, 2, 48, 48))
        self.b2.setText("")
        self.b2.setAutoExclusive(True)
        self.b2.setObjectName("b2")
        self.b3 = QtWidgets.QPushButton(self.buttonGroup)
        self.b3.setEnabled(True)
        self.b3.setGeometry(QtCore.QRect(98, 2, 48, 48))
        self.b3.setText("")
        self.b3.setAutoExclusive(True)
        self.b3.setObjectName("b3")
        self.b4 = QtWidgets.QPushButton(self.buttonGroup)
        self.b4.setGeometry(QtCore.QRect(146, 2, 48, 48))
        self.b4.setText("")
        self.b4.setAutoExclusive(True)
        self.b4.setObjectName("b4")
        self.sizeSlider = QtWidgets.QScrollBar(self.buttonGroup)
        self.sizeSlider.setGeometry(QtCore.QRect(49, 56, 155, 20))
        self.sizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.sizeSlider.setObjectName("sizeSlider")
        self.sizeBox = QtWidgets.QSpinBox(self.buttonGroup)
        self.sizeBox.setGeometry(QtCore.QRect(4, 56, 42, 22))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.sizeBox.setFont(font)
        self.sizeBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sizeBox.setObjectName("sizeBox")
        self.lvncBar = QtWidgets.QProgressBar(self.buttonGroup)
        self.lvncBar.setGeometry(QtCore.QRect(195, 2, 10, 48))
        self.lvncBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lvncBar.setProperty("value", 0)
        self.lvncBar.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lvncBar.setTextVisible(False)
        self.lvncBar.setOrientation(QtCore.Qt.Vertical)
        self.lvncBar.setObjectName("lvncBar")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(1, 444, 211, 193))
        self.frame.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.interpolation = QtWidgets.QComboBox(self.frame)
        self.interpolation.setEnabled(False)
        self.interpolation.setGeometry(QtCore.QRect(0, 80, 209, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.interpolation.setFont(font)
        self.interpolation.setStyleSheet("background-color: rgb(152, 152, 152);")
        self.interpolation.setObjectName("interpolation")
        self.interpolation.addItem("")
        self.interpolation.addItem("")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(0, 55, 209, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(2, 2, 207, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.direction = QtWidgets.QComboBox(self.frame)
        self.direction.setEnabled(False)
        self.direction.setGeometry(QtCore.QRect(2, 27, 209, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.direction.setFont(font)
        self.direction.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.direction.setObjectName("direction")
        self.direction.addItem("")
        self.direction.addItem("")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_5.setGeometry(QtCore.QRect(2, 110, 160, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pixelCount = QtWidgets.QLineEdit(self.frame)
        self.pixelCount.setEnabled(False)
        self.pixelCount.setGeometry(QtCore.QRect(164, 110, 44, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.pixelCount.setFont(font)
        self.pixelCount.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pixelCount.setObjectName("pixelCount")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_6.setGeometry(QtCore.QRect(2, 137, 160, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.connectedPer = QtWidgets.QLineEdit(self.frame)
        self.connectedPer.setEnabled(False)
        self.connectedPer.setGeometry(QtCore.QRect(164, 137, 44, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.connectedPer.setFont(font)
        self.connectedPer.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.connectedPer.setObjectName("connectedPer")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(2, 165, 206, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("background-color: rgb(250, 200, 200);")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.fifo = QtWidgets.QFrame(self.centralwidget)
        self.fifo.setGeometry(QtCore.QRect(0, 0, 211, 222))
        self.fifo.setStyleSheet("background-color: rgb(230, 220, 220);")
        self.fifo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fifo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fifo.setObjectName("fifo")
        self.niiImage = QtWidgets.QPushButton(self.fifo)
        self.niiImage.setEnabled(False)
        self.niiImage.setGeometry(QtCore.QRect(4, 27, 100, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.niiImage.setFont(font)
        self.niiImage.setObjectName("niiImage")
        self.niiSeg = QtWidgets.QPushButton(self.fifo)
        self.niiSeg.setEnabled(False)
        self.niiSeg.setGeometry(QtCore.QRect(108, 27, 100, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.niiSeg.setFont(font)
        self.niiSeg.setObjectName("niiSeg")
        self.line_5 = QtWidgets.QFrame(self.fifo)
        self.line_5.setGeometry(QtCore.QRect(0, 54, 211, 3))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.workspace = QtWidgets.QPushButton(self.fifo)
        self.workspace.setEnabled(True)
        self.workspace.setGeometry(QtCore.QRect(108, 80, 100, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.workspace.setFont(font)
        self.workspace.setStyleSheet("")
        self.workspace.setObjectName("workspace")
        self.dicomImage = QtWidgets.QPushButton(self.fifo)
        self.dicomImage.setEnabled(True)
        self.dicomImage.setGeometry(QtCore.QRect(4, 80, 100, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.dicomImage.setFont(font)
        self.dicomImage.setStyleSheet("")
        self.dicomImage.setDefault(False)
        self.dicomImage.setFlat(False)
        self.dicomImage.setObjectName("dicomImage")
        self.output = QtWidgets.QPushButton(self.fifo)
        self.output.setEnabled(False)
        self.output.setGeometry(QtCore.QRect(3, 139, 203, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.output.setFont(font)
        self.output.setStyleSheet("background-color: rgb(250, 200, 150);")
        self.output.setObjectName("output")
        self.line_2 = QtWidgets.QFrame(self.fifo)
        self.line_2.setGeometry(QtCore.QRect(0, 107, 211, 3))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.batchButton = QtWidgets.QRadioButton(self.fifo)
        self.batchButton.setEnabled(False)
        self.batchButton.setGeometry(QtCore.QRect(3, 109, 203, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.batchButton.setFont(font)
        self.batchButton.setStyleSheet("")
        self.batchButton.setObjectName("batchButton")
        self.line_3 = QtWidgets.QFrame(self.fifo)
        self.line_3.setGeometry(QtCore.QRect(0, 136, 211, 3))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.dicomButton = QtWidgets.QRadioButton(self.fifo)
        self.dicomButton.setEnabled(True)
        self.dicomButton.setGeometry(QtCore.QRect(4, 55, 203, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.dicomButton.setFont(font)
        self.dicomButton.setStyleSheet("")
        self.dicomButton.setChecked(True)
        self.dicomButton.setObjectName("dicomButton")
        self.niftiButton = QtWidgets.QRadioButton(self.fifo)
        self.niftiButton.setEnabled(False)
        self.niftiButton.setGeometry(QtCore.QRect(4, 0, 203, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.niftiButton.setFont(font)
        self.niftiButton.setStyleSheet("")
        self.niftiButton.setCheckable(True)
        self.niftiButton.setChecked(False)
        self.niftiButton.setObjectName("niftiButton")
        self.line = QtWidgets.QFrame(self.fifo)
        self.line.setGeometry(QtCore.QRect(0, 158, 211, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.loadFunBtn = QtWidgets.QPushButton(self.fifo)
        self.loadFunBtn.setGeometry(QtCore.QRect(3, 168, 205, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.loadFunBtn.setFont(font)
        self.loadFunBtn.setStyleSheet("background-color: rgb(200, 255, 200);")
        self.loadFunBtn.setObjectName("loadFunBtn")
        self.imgOrSeg = QtWidgets.QComboBox(self.fifo)
        self.imgOrSeg.setEnabled(False)
        self.imgOrSeg.setGeometry(QtCore.QRect(2, 194, 145, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.imgOrSeg.setFont(font)
        self.imgOrSeg.setStyleSheet("background-color: rgb(180, 200, 220);")
        self.imgOrSeg.setIconSize(QtCore.QSize(25, 25))
        self.imgOrSeg.setObjectName("imgOrSeg")
        self.saveBtn = QtWidgets.QPushButton(self.fifo)
        self.saveBtn.setEnabled(False)
        self.saveBtn.setGeometry(QtCore.QRect(152, 194, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.saveBtn.setFont(font)
        self.saveBtn.setStyleSheet("background-color: rgb(200, 220, 240);")
        self.saveBtn.setText("")
        self.saveBtn.setIconSize(QtCore.QSize(20, 20))
        self.saveBtn.setObjectName("saveBtn")
        self.saveasBtn = QtWidgets.QPushButton(self.fifo)
        self.saveasBtn.setEnabled(False)
        self.saveasBtn.setGeometry(QtCore.QRect(181, 194, 25, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.saveasBtn.setFont(font)
        self.saveasBtn.setStyleSheet("background-color: rgb(200, 220, 240);")
        self.saveasBtn.setText("")
        self.saveasBtn.setIconSize(QtCore.QSize(20, 20))
        self.saveasBtn.setObjectName("saveasBtn")
        self.line.raise_()
        self.niiImage.raise_()
        self.niiSeg.raise_()
        self.line_5.raise_()
        self.workspace.raise_()
        self.dicomImage.raise_()
        self.output.raise_()
        self.line_2.raise_()
        self.batchButton.raise_()
        self.line_3.raise_()
        self.dicomButton.raise_()
        self.niftiButton.raise_()
        self.loadFunBtn.raise_()
        self.imgOrSeg.raise_()
        self.saveBtn.raise_()
        self.saveasBtn.raise_()
        self.emptyFrame = QtWidgets.QFrame(self.centralwidget)
        self.emptyFrame.setGeometry(QtCore.QRect(238, 0, 700, 51))
        self.emptyFrame.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.emptyFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.emptyFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.emptyFrame.setObjectName("emptyFrame")
        self.protocols = QtWidgets.QComboBox(self.emptyFrame)
        self.protocols.setEnabled(True)
        self.protocols.setGeometry(QtCore.QRect(5, 20, 690, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.protocols.setFont(font)
        self.protocols.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.protocols.setCurrentText("")
        self.protocols.setObjectName("protocols")
        self.loadPBar = QtWidgets.QProgressBar(self.emptyFrame)
        self.loadPBar.setGeometry(QtCore.QRect(5, 6, 690, 10))
        self.loadPBar.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.loadPBar.setProperty("value", 0)
        self.loadPBar.setTextVisible(False)
        self.loadPBar.setObjectName("loadPBar")
        self.sliceSlider = QtWidgets.QScrollBar(self.centralwidget)
        self.sliceSlider.setGeometry(QtCore.QRect(945, 160, 16, 486))
        self.sliceSlider.setStyleSheet("background-color: rgb(220, 220, 220);")
        self.sliceSlider.setOrientation(QtCore.Qt.Vertical)
        self.sliceSlider.setObjectName("sliceSlider")
        self.frameSlider = QtWidgets.QScrollBar(self.centralwidget)
        self.frameSlider.setGeometry(QtCore.QRect(345, 760, 486, 16))
        self.frameSlider.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.frameSlider.setOrientation(QtCore.Qt.Horizontal)
        self.frameSlider.setObjectName("frameSlider")
        self.imgFrame = QtWidgets.QScrollArea(self.centralwidget)
        self.imgFrame.setGeometry(QtCore.QRect(240, 56, 700, 700))
        self.imgFrame.setStyleSheet("background-color: rgb(70, 70, 70);")
        self.imgFrame.setWidgetResizable(True)
        self.imgFrame.setObjectName("imgFrame")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 698, 698))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.imgFrame.setWidget(self.scrollAreaWidgetContents)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(2, 780, 928, 83))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("background-color: rgb(180, 250, 180);")
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(25)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(22, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(23, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(24, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        item.setFont(font)
        self.tableWidget.setItem(0, 1, item)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget.verticalHeader().setMinimumSectionSize(30)
        self.exportBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exportBtn.setGeometry(QtCore.QRect(2, 670, 211, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.exportBtn.setFont(font)
        self.exportBtn.setStyleSheet("background-color: rgb(85, 255, 127);")
        self.exportBtn.setObjectName("exportBtn")
        self.Start = QtWidgets.QPushButton(self.centralwidget)
        self.Start.setGeometry(QtCore.QRect(2, 640, 211, 25))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Start.setFont(font)
        self.Start.setStyleSheet("background-color: rgb(250, 200, 200);")
        self.Start.setObjectName("Start")
        self.resetBtn = QtWidgets.QPushButton(self.centralwidget)
        self.resetBtn.setGeometry(QtCore.QRect(2, 728, 209, 28))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setBold(True)
        font.setWeight(75)
        self.resetBtn.setFont(font)
        self.resetBtn.setStyleSheet("background-color: rgb(250, 50, 50);")
        self.resetBtn.setObjectName("resetBtn")
        self.scaleScroll = QtWidgets.QScrollBar(self.centralwidget)
        self.scaleScroll.setGeometry(QtCore.QRect(220, 190, 16, 401))
        self.scaleScroll.setStyleSheet("background-color: rgb(255, 116, 74);")
        self.scaleScroll.setMinimum(1)
        self.scaleScroll.setMaximum(20)
        self.scaleScroll.setProperty("value", 1)
        self.scaleScroll.setOrientation(QtCore.Qt.Vertical)
        self.scaleScroll.setObjectName("scaleScroll")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 963, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelTitle.setText(_translate("MainWindow", "Active Label:"))
        self.paintTitle.setText(_translate("MainWindow", "Paint Over:"))
        self.lineEdit_7.setText(_translate("MainWindow", "Opacity"))
        self.interpolation.setItemText(0, _translate("MainWindow", "x4 cubic"))
        self.interpolation.setItemText(1, _translate("MainWindow", "0.25 mm cubic"))
        self.lineEdit_3.setText(_translate("MainWindow", " Interpolation"))
        self.lineEdit_4.setText(_translate("MainWindow", "   Direction"))
        self.direction.setItemText(0, _translate("MainWindow", "Apex to base"))
        self.direction.setItemText(1, _translate("MainWindow", "Base to Apex"))
        self.lineEdit_5.setText(_translate("MainWindow", "Blood pool pixel count："))
        self.pixelCount.setText(_translate("MainWindow", "64"))
        self.lineEdit_6.setText(_translate("MainWindow", "Minimum connected %:"))
        self.connectedPer.setText(_translate("MainWindow", "50"))
        self.niiImage.setText(_translate("MainWindow", "Image"))
        self.niiSeg.setText(_translate("MainWindow", "Segmentation"))
        self.workspace.setText(_translate("MainWindow", "Workspace"))
        self.dicomImage.setText(_translate("MainWindow", "Image"))
        self.output.setText(_translate("MainWindow", "Intermediate result folder ->"))
        self.batchButton.setText(_translate("MainWindow", "Batch input folder ->"))
        self.dicomButton.setText(_translate("MainWindow", "Dicom"))
        self.niftiButton.setText(_translate("MainWindow", "NIFTI"))
        self.loadFunBtn.setText(_translate("MainWindow", "Load"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "FD"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Slice 1"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Slice 2"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Slice 3"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Slice 4"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Slice 5"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Slice 6"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Slice 7"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Slice 8"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Slice 9"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Slice 10"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Slice 11"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Slice 12"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Slice 13"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Slice 14"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Slice 15"))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Slice 16"))
        item = self.tableWidget.horizontalHeaderItem(16)
        item.setText(_translate("MainWindow", "Slice 17"))
        item = self.tableWidget.horizontalHeaderItem(17)
        item.setText(_translate("MainWindow", "Slice 18"))
        item = self.tableWidget.horizontalHeaderItem(18)
        item.setText(_translate("MainWindow", "Slice 19"))
        item = self.tableWidget.horizontalHeaderItem(19)
        item.setText(_translate("MainWindow", "Slice 20"))
        item = self.tableWidget.horizontalHeaderItem(20)
        item.setText(_translate("MainWindow", "Mean Global FD"))
        item = self.tableWidget.horizontalHeaderItem(21)
        item.setText(_translate("MainWindow", "Mean Basal FD"))
        item = self.tableWidget.horizontalHeaderItem(22)
        item.setText(_translate("MainWindow", "Mean Apical FD"))
        item = self.tableWidget.horizontalHeaderItem(23)
        item.setText(_translate("MainWindow", "Max Basal FD"))
        item = self.tableWidget.horizontalHeaderItem(24)
        item.setText(_translate("MainWindow", "Max Apical FD"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.exportBtn.setText(_translate("MainWindow", "Export Values"))
        self.Start.setText(_translate("MainWindow", "Calculate LVNC"))
        self.resetBtn.setText(_translate("MainWindow", "Reset LVNC FD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

